import type { Trip, Reservation } from "@/store/tripStore";

export const DEMO_TRIP: Trip = {
  id: "demo-paris-viagem-planner",
  name: "Paris — Cidade Luz ✨",
  startDate: "12 jun",
  endDate: "16 jun, 2026",
  totalDays: 5,
  cities: ["Paris"],
  mapCenter: { lat: 48.8566, lng: 2.3522 },
  mapZoom: 13,
  days: [
    { id: 1, label: "Dia 1", date: "12 jun", city: "Paris" },
    { id: 2, label: "Dia 2", date: "13 jun", city: "Paris" },
    { id: 3, label: "Dia 3", date: "14 jun", city: "Paris" },
    { id: 4, label: "Dia 4", date: "15 jun", city: "Paris" },
    { id: 5, label: "Dia 5", date: "16 jun", city: "Paris" },
  ],
  places: [
    // --- Dia 1: Torre Eiffel & Rio Sena ---
    {
      id: 101, dayId: 1,
      title: "Torre Eiffel",
      emoji: "🗼", category: "Atração", color: "from-amber-500 to-orange-500",
      position: { lat: 48.8584, lng: 2.2945 },
      time: "09:00", duration: "2h",
      note: "Compre ingressos online com antecedência — filas são enormes!",
      description: "O símbolo máximo de Paris. Suba ao 2º andar para a vista mais fotogênica. O andar superior tem um champanhe bar com vista de 360°.",
      address: "Champ de Mars, 5 Av. Anatole France, 75007 Paris",
      rating: 4.7, website: "https://www.toureiffel.paris",
    },
    {
      id: 102, dayId: 1,
      title: "Jardim do Champ de Mars",
      emoji: "🌿", category: "Parque", color: "from-green-500 to-emerald-600",
      position: { lat: 48.8562, lng: 2.2978 },
      time: "11:30", duration: "1h",
      note: "Perfeito para um piquenique com baguete e queijo local",
      description: "O imenso parque que se estende aos pés da Torre Eiffel. Um clássico para relaxar, tirar fotos e observar a vida parisiense.",
      address: "Champ de Mars, 75007 Paris",
      rating: 4.5,
    },
    {
      id: 103, dayId: 1,
      title: "Café de Flore",
      emoji: "☕", category: "Restaurante", color: "from-emerald-500 to-teal-600",
      position: { lat: 48.8536, lng: 2.3264 },
      time: "13:30", duration: "1h30",
      note: "Peça o croque-monsieur e o chocolat chaud — são famosos!",
      description: "Um dos cafés mais históricos de Paris. Frequentado por Sartre, Simone de Beauvoir e Picasso. Atmosfera literária inigualável em Saint-Germain-des-Prés.",
      address: "172 Bd Saint-Germain, 75006 Paris",
      rating: 4.2, website: "https://cafedeflore.fr",
    },
    {
      id: 104, dayId: 1,
      title: "Cruzeiro pelo Rio Sena",
      emoji: "🚢", category: "Passeio", color: "from-sky-500 to-blue-600",
      position: { lat: 48.8566, lng: 2.3515 },
      time: "18:00", duration: "1h30",
      note: "O horário do pôr do sol é o mais bonito. Reserve lugar no deck superior.",
      description: "Veja 15 monumentos históricos de Paris em um passeio relaxante pelo Sena. A iluminação noturna da cidade é de tirar o fôlego.",
      address: "Port de la Bourdonnais, 75007 Paris",
      rating: 4.5, website: "https://www.bateaux-mouches.fr",
    },

    // --- Dia 2: Louvre e Notre-Dame ---
    {
      id: 201, dayId: 2,
      title: "Museu do Louvre",
      emoji: "🎨", category: "Museu", color: "from-violet-500 to-purple-600",
      position: { lat: 48.8606, lng: 2.3376 },
      time: "09:30", duration: "3h",
      note: "Vá direto para a Mona Lisa (Salle 711) ao entrar — as filas crescem rápido.",
      description: "O maior museu de arte do mundo com 35.000 obras. Além da Mona Lisa, não perca a Vênus de Milo e a Vitória de Samotrácia. Entrada gratuita no 1º domingo do mês.",
      address: "Rue de Rivoli, 75001 Paris",
      rating: 4.8, website: "https://www.louvre.fr",
    },
    {
      id: 202, dayId: 2,
      title: "Jardim das Tulherias",
      emoji: "🌷", category: "Parque", color: "from-green-500 to-emerald-600",
      position: { lat: 48.8636, lng: 2.3279 },
      time: "13:00", duration: "1h",
      note: "Ideal para uma pausa com sorvete antes de continuar o passeio",
      description: "Jardim histórico entre o Louvre e a Place de la Concorde. Esculturas espalhadas pelos gramados e uma vista privilegiada da Torre Eiffel ao longe.",
      address: "Place de la Concorde, 75001 Paris",
      rating: 4.4,
    },
    {
      id: 203, dayId: 2,
      title: "Sainte-Chapelle",
      emoji: "⛪", category: "Monumento", color: "from-indigo-500 to-blue-600",
      position: { lat: 48.8554, lng: 2.3450 },
      time: "15:00", duration: "1h",
      note: "Os vitrais ficam mais impressionantes com sol da tarde",
      description: "Uma das obras-primas da arquitetura gótica. Os 15 vitrais de 13 metros são considerados os mais belos do mundo. Escondida no complexo da Cité, é uma joia subestimada.",
      address: "8 Bd du Palais, 75001 Paris",
      rating: 4.7,
    },
    {
      id: 204, dayId: 2,
      title: "Notre-Dame de Paris",
      emoji: "🕌", category: "Monumento", color: "from-indigo-500 to-blue-600",
      position: { lat: 48.8530, lng: 2.3499 },
      time: "17:00", duration: "1h30",
      note: "Atração em reconstrução — a fachada já pode ser admirada do lado de fora",
      description: "A catedral gótica mais famosa do mundo, em plena restauração após o incêndio de 2019. A visita à ilha da Cité ao redor da catedral já vale o passeio.",
      address: "Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris",
      rating: 4.7,
    },

    // --- Dia 3: Versalhes ---
    {
      id: 301, dayId: 3,
      title: "Palácio de Versalhes",
      emoji: "🏰", category: "Atração", color: "from-amber-500 to-orange-500",
      position: { lat: 48.8049, lng: 2.1204 },
      time: "09:00", duration: "4h",
      note: "Pegue o RER C da estação Saint-Michel. Evite segundas (fechado).",
      description: "A residência real mais suntuosa da Europa. A Galeria dos Espelhos, os aposentos reais e o Grand Trianon são imperdíveis. Reserve meio dia inteiro.",
      address: "Place d'Armes, 78000 Versailles",
      rating: 4.7, website: "https://www.chateauversailles.fr",
    },
    {
      id: 302, dayId: 3,
      title: "Jardins de Versalhes",
      emoji: "🌳", category: "Parque", color: "from-green-500 to-emerald-600",
      position: { lat: 48.8048, lng: 2.1138 },
      time: "13:30", duration: "2h",
      note: "Alugue um barco no Grand Canal — é a experiência mais pitoresca",
      description: "800 hectares de jardins à francesa projetados por Le Nôtre. Fontes, estátuas, bosques e o Grande Canal onde a realeza passeava de gôndola.",
      address: "78000 Versailles",
      rating: 4.6,
    },
    {
      id: 303, dayId: 3,
      title: "Jantar em Saint-Germain-des-Prés",
      emoji: "🍷", category: "Restaurante", color: "from-emerald-500 to-teal-600",
      position: { lat: 48.8529, lng: 2.3319 },
      time: "19:30", duration: "2h",
      note: "Bairro cheio de bistrôs autênticos — explore sem pressa",
      description: "O bairro boêmio de Paris é perfeito para um jantar descontraído. Bistrôs aconchegantes, vinho natural e a melhor crème brûlée da cidade.",
      address: "Saint-Germain-des-Prés, 75006 Paris",
      rating: 4.5,
    },

    // --- Dia 4: Montmartre e Champs-Élysées ---
    {
      id: 401, dayId: 4,
      title: "Basílica do Sacré-Cœur",
      emoji: "⛪", category: "Monumento", color: "from-indigo-500 to-blue-600",
      position: { lat: 48.8867, lng: 2.3431 },
      time: "09:30", duration: "1h30",
      note: "Suba a pé pela Rue Lepic para a experiência mais parisiense",
      description: "A basílica branca no topo da colina de Montmartre oferece uma das vistas mais bonitas de Paris. A entrada é gratuita e o interior é majestoso.",
      address: "35 Rue du Chevalier de la Barre, 75018 Paris",
      rating: 4.7,
    },
    {
      id: 402, dayId: 4,
      title: "Place du Tertre — Artistas",
      emoji: "🖼️", category: "Atração", color: "from-amber-500 to-orange-500",
      position: { lat: 48.8866, lng: 2.3406 },
      time: "11:30", duration: "1h",
      note: "Artistas fazem retratos ao vivo — uma lembrança única de Paris",
      description: "A praça dos artistas de Montmartre, onde pintores expõem e vendem suas obras desde o século XIX. Atmosfera boêmia e charmosa.",
      address: "Place du Tertre, 75018 Paris",
      rating: 4.3,
    },
    {
      id: 403, dayId: 4,
      title: "Galeries Lafayette",
      emoji: "🛍️", category: "Compras", color: "from-pink-500 to-rose-600",
      position: { lat: 48.8737, lng: 2.3324 },
      time: "14:00", duration: "2h",
      note: "Suba ao terraço — a vista da cúpula e da cidade é de graça e deslumbrante",
      description: "O mais famoso grand magasin de Paris com a espetacular cúpula Art Nouveau. Moda, gastronomia e souvenirs de alta qualidade em 9 andares.",
      address: "40 Bd Haussmann, 75009 Paris",
      rating: 4.4, website: "https://www.galerieslafayette.com",
    },
    {
      id: 404, dayId: 4,
      title: "Champs-Élysées ao entardecer",
      emoji: "🌆", category: "Passeio", color: "from-sky-500 to-blue-600",
      position: { lat: 48.8698, lng: 2.3078 },
      time: "17:00", duration: "2h",
      note: "Acabe o passeio no Arc de Triomphe para ver a avenida iluminada de cima",
      description: "A avenida mais famosa do mundo com 1,9 km de lojas, cafés e teatros. Terminar o dia vendo as luzes acenderem é uma experiência inesquecível.",
      address: "Av. des Champs-Élysées, 75008 Paris",
      rating: 4.4,
    },

    // --- Dia 5: Arc de Triomphe & Museu d'Orsay ---
    {
      id: 501, dayId: 5,
      title: "Arc de Triomphe",
      emoji: "🏛️", category: "Monumento", color: "from-indigo-500 to-blue-600",
      position: { lat: 48.8738, lng: 2.2950 },
      time: "09:00", duration: "1h30",
      note: "A vista do topo mostra 12 avenidas irradiando do arco — impressionante!",
      description: "Mandado construir por Napoleão, o arco de 50 metros homenageia os soldados franceses. Do topo, a visão dos Champs-Élysées é icônica.",
      address: "Pl. Charles de Gaulle, 75008 Paris",
      rating: 4.7,
    },
    {
      id: 502, dayId: 5,
      title: "Museu d'Orsay",
      emoji: "🖼️", category: "Museu", color: "from-violet-500 to-purple-600",
      position: { lat: 48.8600, lng: 2.3266 },
      time: "11:00", duration: "2h30",
      note: "Monet, Renoir, Van Gogh, Degas — a coleção impressionista é insuperável",
      description: "Instalado em uma antiga estação de trem, abriga a maior coleção de arte impressionista do mundo. O relógio da estação emoldura uma vista única do Sena.",
      address: "1 Rue de la Légion d'Honneur, 75007 Paris",
      rating: 4.8, website: "https://www.musee-orsay.fr",
    },
    {
      id: 503, dayId: 5,
      title: "Almoço de despedida — Brasserie Lipp",
      emoji: "🥂", category: "Restaurante", color: "from-emerald-500 to-teal-600",
      position: { lat: 48.8534, lng: 2.3321 },
      time: "14:00", duration: "2h",
      note: "Peça o foie gras de entrada e o magret de canard — clássicos da casa",
      description: "Uma das brasseries mais clássicas de Paris, aberta desde 1880. Decoração Art Nouveau, serviço impecável e cozinha alsaciana autêntica.",
      address: "151 Bd Saint-Germain, 75006 Paris",
      rating: 4.5,
    },
    {
      id: 504, dayId: 5,
      title: "Île Saint-Louis — Sorbet Berthillon",
      emoji: "🍨", category: "Passeio", color: "from-sky-500 to-blue-600",
      position: { lat: 48.8509, lng: 2.3561 },
      time: "16:30", duration: "1h",
      note: "Sorvete Berthillon é o mais famoso de Paris — fila pode ser grande",
      description: "A ilha mais charmosa de Paris com ruas medievais, galerias de arte e o lendário sorvete Berthillon. O passeio à beira do Sena ao entardecer é perfeito.",
      address: "Île Saint-Louis, 75004 Paris",
      rating: 4.6,
    },
  ],
  wishlist: [
    {
      id: 901,
      title: "Centre Pompidou",
      emoji: "🎭", category: "Museu", color: "from-violet-500 to-purple-600",
      position: { lat: 48.8607, lng: 2.3521 },
      address: "Pl. Georges-Pompidou, 75004 Paris",
      note: "Museu de arte moderna com arquitetura futurista icônica. Vista do terraço vale o ingresso.",
      rating: 4.4,
    },
    {
      id: 902,
      title: "Disneyland Paris",
      emoji: "🏰", category: "Atração", color: "from-amber-500 to-orange-500",
      position: { lat: 48.8674, lng: 2.7820 },
      address: "Bd de Parc, 77700 Coupvray",
      note: "1h de Paris de trem (RER A). Reserve 1 dia inteiro e compre ingressos com antecedência.",
      rating: 4.5,
    },
    {
      id: 903,
      title: "Catacombes de Paris",
      emoji: "💀", category: "Atração", color: "from-amber-500 to-orange-500",
      position: { lat: 48.8339, lng: 2.3329 },
      address: "1 Av. du Colonel Henri Rol-Tanguy, 75014 Paris",
      note: "6 milhões de crânios e ossos em túneis subterrâneos. Ingressos se esgotam semanas antes.",
      rating: 4.6,
    },
    {
      id: 904,
      title: "Château de Fontainebleau",
      emoji: "🏯", category: "Monumento", color: "from-indigo-500 to-blue-600",
      position: { lat: 48.4024, lng: 2.7015 },
      address: "77300 Fontainebleau",
      note: "45min de Paris de trem. Muito menos turistas que Versalhes e igualmente impressionante.",
      rating: 4.6,
    },
  ],
  receipts: [],
};

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 1001,
    type: "flight",
    title: "Voo GRU → CDG (Air France)",
    provider: "Air France",
    confirmationCode: "AF7842GRU",
    startDate: "12 jun",
    endDate: "12 jun",
    startTime: "22:15",
    endTime: "14:30",
    origin: "GRU — São Paulo/Guarulhos",
    destination: "CDG — Paris Charles de Gaulle",
    cost: 4850,
    currency: "BRL",
    notes: "Assento 24A (janela). Check-in online abre 30h antes. Bagagem despachada: 23kg incluída.",
  },
  {
    id: 1002,
    type: "flight",
    title: "Voo CDG → GRU (Air France)",
    provider: "Air France",
    confirmationCode: "AF7843CDG",
    startDate: "16 jun",
    endDate: "17 jun",
    startTime: "16:45",
    endTime: "05:20",
    origin: "CDG — Paris Charles de Gaulle",
    destination: "GRU — São Paulo/Guarulhos",
    cost: 4850,
    currency: "BRL",
    notes: "Chegada no dia seguinte. Confirme o assento com antecedência no site da companhia.",
  },
  {
    id: 1003,
    type: "hotel",
    title: "Hôtel Le Petit Belloy — Saint-Germain",
    provider: "Booking.com",
    confirmationCode: "BK-9947823",
    startDate: "12 jun",
    endDate: "16 jun",
    location: "11 Rue Casimir Delavigne, 75006 Paris",
    cost: 1240,
    currency: "EUR",
    notes: "Café da manhã continental incluso. Check-in a partir das 15h. Check-out até 11h. Cancellation free até 5 dias antes.",
  },
  {
    id: 1004,
    type: "restaurant",
    title: "Jantar — Jules Verne (Torre Eiffel)",
    provider: "Opentable",
    confirmationCode: "OT-882341",
    startDate: "12 jun",
    startTime: "20:00",
    endTime: "22:30",
    location: "2º andar da Torre Eiffel, Paris",
    cost: 360,
    currency: "EUR",
    notes: "Reserva para 2 pessoas. Dress code elegante obrigatório. Vista panorâmica de Paris durante o jantar.",
  },
  {
    id: 1005,
    type: "car",
    title: "Transfer Aeroporto → Hotel",
    provider: "G7 Taxi Paris",
    confirmationCode: "G7-55218",
    startDate: "12 jun",
    startTime: "15:00",
    origin: "CDG — Terminal 2E",
    destination: "Hôtel Le Petit Belloy, Saint-Germain",
    cost: 75,
    currency: "EUR",
    notes: "Motorista aguardará com placa no nome. Pagamento em dinheiro ou cartão.",
  },
];
